spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    driver-class-name: org.h2.Driver
    url: ${LOCAL_DB_URL}
    username: ${LOCAL_DB_USERNAME}
    password: ${LOCAL_DB_PASSWORD}

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

jwt:
  secret:
    key: ${JWT_SECRET_KEY}
  token:
    access-token-expiration-millis: 900000

oauth:
  kakao:
    client_id: ${KAKAO_RESTAPI_KEY}
    client_secret: ${KAKAO_CLIENT_SECRET_KEY}
    redirect_uri: http://localhost:8080/kakao/callback
    request_uri:
      auth: https://kauth.kakao.com # 카카오 인증 서버로 토큰 값 요청
      api: https://kapi.kakao.com # 카카오 서버로 사용자 정보 요청
  google:
    client_id: ${GOOGLE_CLIENT_ID}
    client_secret: ${GOOGLE_CLIENT_SECRET}
    redirect_uri: http://localhost:8080/google/callback
    request_uri:
      auth: https://oauth2.googleapis.com/token
      api: https://www.googleapis.com/oauth2/v1/userinfo
  naver:
    client_id: ${NAVER_CLIENT_ID}
    client_secret: ${NAVER_CLIENT_SECRET}
    redirect_uri: http://localhost:8080/naver/callback
    request_uri:
      auth: https://nid.naver.com/oauth2.0/token
      api: https://openapi.naver.com/v1/nid/me
